config/routes.rb
Rails.application.routes.draw do
  get 'reader/index'

  root 'reader#index'

  get "book/:book_number/chapter/:chapter_number/verse/:verse_number",  to: "reader#verse"
  get "book/:book_number/chapter/:chapter_number",                      to: "reader#chapter"
  get "book/:book_number",                                              to: "reader#book"

  resources :book do
    resources :chapter do
      resources :verse
    end
  end

end

app/models/book.rb
class Book < ActiveRecord::Base
  # title

  has_many :chapters
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  # book_nunber (integer)
  # chapter_number (integer)

  belongs_to :book
  has_many :verses

end

app/models/verse.rb
class Verse < ActiveRecord::Base
  # translation (string)
  # book_number (integer)
  # chapter_number (integer)
  # verse_number (integer)
  # body (text)

  belongs_to :chapter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/reader_controller.rb
class ReaderController < ApplicationController

  def index
    @books          = Book.all
  end

  def book
    @book_number    = params[:book_number]
    @book_title     = params[:book_title]
    render "book", layout: false
  end

  def chapter
    @book_number    = params[:book_number]
    @chapter_number = params[:chapter_number]
    @chapter_text   = params[:chapter_text]
    render "chapter", layout: false
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reader_helper.rb
module ReaderHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bible</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <!-- FAVICON -->
	<link rel="icon" type="image/png" href="/img/favicon.png" />

	<!-- IOS -->
	<meta name="apple-mobile-web-app-title" content="Jeff Batterton">
	<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
	<link rel="apple-touch-icon-precomposed" href="/apple-touch-icon-precomposed.png">
	<link rel="apple-touch-icon-precomposed" sizes="72x72" href="/apple-touch-icon-72x72-precomposed.png">
	<link rel="apple-touch-icon-precomposed" sizes="114x114" href="/apple-touch-icon-114x114-precomposed.png">
	<link rel="apple-touch-icon-precomposed" sizes="144x144" href="/apple-touch-icon-144x144-precomposed.png">

</head>

<%= yield %>

</html>

app/views/reader/_book_menu.html.erb
<ul>
  <% @books.each do |book| %>
    <%= content_tag :li do %>
      <%= link_to book.title, book_path(book.id), data: { "book-number" => book.id } %>
    <% end %>
  <% end %>
</ul>

app/views/reader/book.html.erb
<% if @book_title %>
  <%= Book.find(@book_number).title %>
<% else %>
  <h3>Chapter</h3>
  <ul>
    <% Chapter.where(book_number: @book_number).find_each do |chapter| %>
      <%= content_tag :li do %>
        <%= link_to chapter.chapter_number, book_chapter_path(@book_number, chapter.chapter_number), data: { chapter_number: chapter.chapter_number } %>
      <% end %>
    <% end %>
  </ul>
<% end %>

app/views/reader/chapter.html.erb
<% if @chapter_text %>
  <div class="chapter" data-chapter-number="<%= @chapter_number %>" data-book-number="<%= @book_number %>">
    <h3>Chapter <%= @chapter_number %></h3>
    <% Verse.where(book_number: @book_number, chapter_number: @chapter_number).find_each do |verse| %>
      <%= content_tag :p do %>
        <%= link_to verse.verse_number, book_chapter_verse_path(@book_number, @chapter_number, verse.verse_number) %>
        <%= verse.body %>
      <% end %>
    <% end %>
  </div>
<% else %>
  <h3>Verse</h3>
  <ul>
    <% Verse.where(book_number: @book_number, chapter_number: @chapter_number).find_each do |verse| %>
      <%= content_tag :li do %>
        <%= link_to verse.verse_number, book_chapter_verse_path(@book_number, @chapter_number, verse.verse_number) %>
      <% end %>
    <% end %>
  </ul>
<% end %>

app/views/reader/index.html.erb
<body data-active-section="books" data-book-number="1">

  <%= audio_tag("click.wav", id: "sound-click", preload: "auto") %>
  <%= audio_tag("swipe.wav", id: "sound-swipe", preload: "auto") %>

  <header>
    <%= link_to root_path do %>
      <i class="icon-back"></i>
      <span id="back-link">Back</span>
    <% end %>
    <h1><span id="book-title-container">Genesis</span><span id="chapter-number-container"></span></h1>
    <div id="faux-header"></div>
  </header>

  <div class="container">

    <section id="books">
      <%= render "book_menu" %>
    </section>

    <section id="chapters">
      <div id="chapter-container">
      </div>
      <div id="verse-container">
      </div>
    </section>

    <section id="reader">
      <div class="content">
      </div>
    </section>

  </div>

</body>